apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-bus-depl
  labels:
    app: events-bus
spec:
  replicas: 1
  template:
    metadata:
      name: events-bus-depl
      labels:
        app: events-bus
    spec:
      containers:
        - name: events-bus-depl
          image: blessayaf/events-bus
      restartPolicy: Always
  selector:
    matchLabels:
      app: events-bus


