apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl
  labels:
    app: posts
spec:
  replicas: 1
  template:
    metadata:
      name: posts-depl
      labels:
        app: posts
    spec:
      containers:
        - name: posts-depl
          image: blessayaf/posts
      restartPolicy: Always
  selector:
    matchLabels:
      app: posts


